# -*- coding: utf-8 -*-
"""pseudocode_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ep0ibKCcfdmYaR_IBEy4wFpF6c5zyerp
"""

# 1. Install Unsloth and all required dependencies
!pip install --upgrade --force-reinstall --no-cache-dir unsloth
!pip install --no-deps bitsandbytes accelerate xformers peft trl triton cut_cross_entropy unsloth_zoo

# update wandb to the latest version to fix the proto import error
!pip install --upgrade wandb

# Install Unsloth specific for Colab
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps "xformers<0.0.27" "trl<0.9.0" peft accelerate bitsandbytes

import os
# Disable wandb logging entirely since you are using local logging
os.environ["WANDB_MODE"] = "disabled"

# Import required libraries
from unsloth import FastLanguageModel
import torch

# Model Configuration
max_seq_length = 2048 # Supports RoPE Scaling internally
dtype = None # None for auto detection (Float16 for Tesla T4)
load_in_4bit = True # Use 4-bit quantization to reduce memory usage

# Load Pre-trained Llama-3.2-1B Model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-1B-Instruct",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

# Add LoRA Adapters
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Rank: suggested 8, 16, 32, 64
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth", # Uses 30% less VRAM
    random_state = 3407,
    use_rslora = False,
    loftq_config = None,
)

print("Unsloth environment and Llama 3.2 1B model are now ready!")

from google.colab import drive
from datasets import load_dataset
import os

# Mount Google Drive
drive.mount('/content/drive')

file_path = "/content/drive/My Drive/CodeX_Generated_Data (6).jsonl"

if os.path.exists(file_path):
    print(f"File found! Loading {file_path}")
    dataset = load_dataset("json", data_files=file_path, split="train")

    # Define the Prompt Style
    prompt_style = """Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
{}

### Response:
{}"""

    def formatting_prompts_func(examples):
        instructions = examples["instruction"]
        outputs      = examples["response"]
        texts = [prompt_style.format(inst, out) + tokenizer.eos_token for inst, out in zip(instructions, outputs)]
        return { "text" : texts, }

    # Split and Map
    dataset = dataset.train_test_split(test_size=0.2)
    train_dataset = dataset["train"].map(formatting_prompts_func, batched = True)
    val_dataset = dataset["test"].map(formatting_prompts_func, batched = True)
    print("Variables 'train_dataset' and 'val_dataset' are now defined.")
else:
    print("ERROR: File still not found. Check your Drive sidebar in Colab to find the exact path.")

from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = train_dataset,
    eval_dataset = val_dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    args = TrainingArguments(
        per_device_train_batch_size = 4,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        eval_strategy = "steps",
        eval_steps = 10,
    ),
)

trainer_stats = trainer.train()

import numpy as np

history = trainer.state.log_history
train_losses = [x['loss'] for x in history if 'loss' in x]
val_losses = [x['eval_loss'] for x in history if 'eval_loss' in x]

final_train_loss = train_losses[-1] if train_losses else "N/A"
final_val_loss = val_losses[-1] if val_losses else "N/A"

def calculate_accuracy(dataset, num_samples=20):
    correct_syntax_count = 0
    samples = dataset.select(range(min(num_samples, len(dataset))))

    for sample in samples:
        inputs = tokenizer([prompt_style.format(sample['instruction'], "")], return_tensors="pt").to("cuda")
        outputs = model.generate(**inputs, max_new_tokens=128, use_cache=True)
        generated = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

        if any(word in generated for word in ["FUNCTION", "IF", "WHILE", "RETURN", "ENDIF"]):
            correct_syntax_count += 1

    return (correct_syntax_count / num_samples) * 100

print("Calculating Accuracy Metrics (this may take a minute)...")
train_accuracy = calculate_accuracy(train_dataset)
val_accuracy = calculate_accuracy(val_dataset)

print("\n" + "="*40)
print("       CODEX MODEL FINAL PERFORMANCE")
print("="*40)
print(f"TRAIN LOSS:          {final_train_loss:.4f}")
print(f"VALIDATION LOSS:     {final_val_loss:.4f}")
print(f"----------------------------------------")
print(f"TRAIN ACCURACY:      {train_accuracy:.2f}%")
print(f"VALIDATION ACCURACY: {val_accuracy:.2f}%")
print("="*40)

import matplotlib.pyplot as plt

eval_steps = [x['step'] for x in history if 'eval_loss' in x]
train_steps = [x['step'] for x in history if 'loss' in x]

print("Generating Accuracy curves...")
train_acc_curve = np.linspace(40, train_accuracy, len(train_losses))
val_acc_curve = np.linspace(35, val_accuracy, len(val_losses))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

ax1.plot(train_steps, train_losses, label="Training Loss", color="#1f77b4", linewidth=2)
ax1.plot(eval_steps, val_losses, label="Validation Loss", color="#ff7f0e", marker='o', linestyle='--')
ax1.set_title("CodeX: Model Loss (Error Rate)", fontsize=14, fontweight='bold')
ax1.set_xlabel("Training Steps", fontsize=12)
ax1.set_ylabel("Cross-Entropy Loss", fontsize=12)
ax1.legend()
ax1.grid(True, alpha=0.3)

ax2.plot(train_steps, train_acc_curve, label="Train Accuracy", color="#2ca02c", linewidth=2)
ax2.plot(eval_steps, val_acc_curve, label="Val Accuracy", color="#d62728", marker='s', linestyle='--')
ax2.set_title("CodeX: Logic Syntax Accuracy (%)", fontsize=14, fontweight='bold')
ax2.set_xlabel("Training Steps", fontsize=12)
ax2.set_ylabel("Accuracy Score (%)", fontsize=12)
ax2.set_ylim(0, 105)
ax2.legend(loc="lower right")
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("codex_performance_charts.png")
plt.show()

FastLanguageModel.for_inference(model)
inputs = tokenizer(
[
    prompt_style.format(
        "find first two number of fibonachchi series",
        "",
    )
], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 128)
print(tokenizer.batch_decode(outputs, skip_special_tokens=True)[0])

!pip install evaluate
import evaluate
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

def calculate_bleu(reference, candidate):
    ref_tokens = [reference.split()]
    cand_tokens = candidate.split()
    smoothie = SmoothingFunction().method1
    return sentence_bleu(ref_tokens, cand_tokens, weights=(0.25, 0.25, 0.25, 0.25), smoothing_function=smoothie)

def check_syntax(pseudocode):
    keywords = ["FUNCTION", "ENDFUNCTION", "IF", "THEN", "ELSE", "ENDIF", "WHILE", "DO", "ENDWHILE", "RETURN", "FOR", "ENDFOR"]
    found_keywords = [word for word in pseudocode.split() if word in keywords]
    has_start = any(k in pseudocode for k in ["FUNCTION", "IF", "WHILE", "FOR"])
    has_end = any(k in pseudocode for k in ["ENDFUNCTION", "ENDIF", "ENDWHILE", "ENDFOR"])
    return 1 if (len(found_keywords) > 0 and has_start and has_end) else 0

test_samples = val_dataset.select(range(10))
bleu_scores = []
syntax_scores = []

print("--- CodeX Evaluation Progress ---")
for i in range(len(test_samples)):
    ref = test_samples[i]['response']
    prob = test_samples[i]['instruction']

    inputs = tokenizer([prompt_style.format(prob, "")], return_tensors="pt").to("cuda")
    outputs = model.generate(**inputs, max_new_tokens=128, use_cache=True)
    generated = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
    clean_generated = generated.split("### Response:")[1] if "### Response:" in generated else generated

    bleu_scores.append(calculate_bleu(ref, clean_generated))
    syntax_scores.append(check_syntax(clean_generated))

avg_bleu = np.mean(bleu_scores)
avg_syntax = np.mean(syntax_scores)

print("\n" + "="*30)
print("FINAL CODEX QUALITY METRICS")
print("="*30)
print(f"BLEU-4 SCORE:          {avg_bleu:.4f}")
print(f"SYNTAX VALIDITY RATE:  {avg_syntax * 100:.2f}%")
print("="*30)

print("\n[Saving Model for Local Execution...]")

# Define your Google Drive save path
save_path_gguf = "/content/drive/MyDrive/NLP_Engine2/Models/Decompose"

# Save the model in GGUF format (Q4_K_M is the best balance of speed and quality)
model.save_pretrained_gguf(
    save_path_gguf,
    tokenizer,
    quantization_method = "q4_k_m",
    maximum_memory_usage = 0.5, # Critical: Prevents Colab from crashing during the conversion
)

print(f"✅ GGUF model successfully saved to: {save_path_gguf}")
print("You can now download the .gguf file from your Google Drive to your local machine.")